[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_counter = "6s254XijhqqRP6Yn9FpSgKrNNbGrj9cD64QuRfTXjici"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/aeres/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
